### ISSUE TITLE
I'm new to this, but how do I make it do anything?

### ISSUE THREAD

**Issue by LloydLTZ** [Blockzilla101/citation#5]
I'm not very knowledgeable on coding, but I was wondering how I'm supposed to make this work.

**Comment by Blockzilla101** [comment]
Install node & npm, then create a node.js project. It was tested with v19 I don't know if it still works with the latest version v23. 

Then you can install this library using the command on readme and copy paste the code into a js file e.g `index.js`. Run it using `node index.js`.

If it works you should see a two image files in the same folder as `index.js`

**Comment by LloydLTZ** [comment]
I'm sorry if I seem really dumb, but how do I make a node.js project? I have node and npm installed, but I have no idea what I'm doing here.

**Comment by Blockzilla101** [comment]
you can just run `npm init`

**Comment by LloydLTZ** [comment]
... Nothing's happened.

**Comment by Blockzilla101** [comment]
It should ask you the project name

**Comment by LloydLTZ** [comment]
It shows the name now.
![image](https://github.com/user-attachments/assets/8ae2005f-2fc7-4237-8085-5ed0ce91927b)

**Comment by Blockzilla101** [comment]
Answer those questions and it should create a folder with the name you have provided along with some files inside it

**Comment by LloydLTZ** [comment]
When it says "Is this Okay? (yes)", it seems to not take me putting in Y, y, or Yes.

**Comment by Blockzilla101** [comment]
Press enter then it should take yes as default

**Comment by LloydLTZ** [comment]
All it seems to have done is create a package.json file and nothing else.

**Comment by Blockzilla101** [comment]
That's correct, you can install this library now using the command on readme

**Comment by Blockzilla101** [comment]
Run this in the same folder as package.json

**Comment by LloydLTZ** [comment]
And that gives all the files that are on the github, right? Got a whole folder with your username as its label.

**Comment by Blockzilla101** [comment]
It will download this library into node_modules as well add it to package.json

**Comment by LloydLTZ** [comment]
And how do I make use of the library itself?

**Comment by Blockzilla101** [comment]
Copy paste the code in readme into index.js and run it using node index.js

**Comment by LloydLTZ** [comment]
I have no idea how I do that. Is that what I put into command prompt?

**Comment by Blockzilla101** [comment]
After making the index.js file yes

**Comment by Blockzilla101** [comment]
Copy paste the code into any editor and save it as index.js

**Comment by LloydLTZ** [comment]
![image](https://github.com/user-attachments/assets/2eee99d1-54af-43e1-9b16-d410adbf1b75)
It isn't directing to the right folder. It should be going to lloyd/node_modules/@Blockzilla101 folder instead, right? I have no idea how to redirect it.

**Comment by Blockzilla101** [comment]
The file name is incorrect

**Comment by LloydLTZ** [comment]
Tried fixing it, and it gives the same error.

**Comment by Blockzilla101** [comment]
Did you place in it in the correct folder? it should in the same one as package.json

**Comment by LloydLTZ** [comment]
![image](https://github.com/user-attachments/assets/c0555d4d-1177-4377-a98e-e753d108595b)
It's all in the same folder.

**Comment by LloydLTZ** [comment]
![image](https://github.com/user-attachments/assets/101ce039-5ffc-4a8e-9a02-c958f0322930)
This is what the error window says.

**Comment by Blockzilla101** [comment]
That's not the correct place to put

**Comment by Blockzilla101** [comment]
place it in lloyd

**Comment by Blockzilla101** [comment]
You might have also overwritten the one from the library

**Comment by Blockzilla101** [comment]
Honestly, just follow a guide on yt for how to make a hello world node.js application

**Comment by Blockzilla101** [comment]
Reopen this issue if there are any errors are after running the code in the readme.
